### ISSUE TITLE
Swif4

### ISSUE THREAD

**Issue by asfcarvalho** [takenet/blip-chat-ios#1]
this version isn't compatible with swift 4. how i fix this?

**Comment by VictorBalbo** [comment]
Hi @asfcarvalho,
We've just updated the pod with support for Swift 4.

**Comment by asfcarvalho** [comment]
Thanks

Enviado do meu iPhone

Em 25 de out de 2017, à(s) 15:56, Victor Balbo <notifications@github.com> escreveu:
